### PR TITLE
Adding TabIcon property to PluginControlBase

### PR DESCRIPTION
**Pull request by rappen**
Adding ``TabIcon`` property to ``PluginControlBase`` making it possible to display custom 16x16 icon in the tab for a plugin.

Example:
image

Properties of the PluginControl:
image

### CODE REVIEW

**Comment by MscrmTools** [comment]
@rappen thanks for this PR but it seems you forgot something. The build failed:
MainForm.PluginsManagement.cs(185,21): error CS0103: The name 'pluginTabsImagesList' does not exist in the current context [C:\projects\xrmtoolbox\XrmToolBox\XrmToolBox.csproj]

**Comment by rappen** [comment]
Ooops. Did the fix from me now solve the problem?

**Comment by MscrmTools** [comment]
Yes it did

**Comment by daryllabar** [comment]
I'm assuming that the Plugin Interface was updated as well?

**Comment by MscrmTools** [comment]
It's the plugin control base that have been extended with a new property. No breaking change

**Comment by rappen** [comment]
Branding is fun!

image

And so much easier to find the right tab ;-)

**Comment by daryllabar** [comment]
Now we just need to add a close tab icon...

**Comment by rappen** [comment]
Now using icon in menu items too.
https://github.com/MscrmTools/XrmToolBox/commit/8ffac4a760f12ada4b4ce8f2ea9ee200400fc1e1

**Pull request merged**
