### PR TITLE
Rename web resources in Web Resource Manager

### PR DESCRIPTION
**Pull request by shytikov**
I'm sick and tired of fact that it's impossible to change name to web resources, if, for example, typo happened during creation of it. So this PR is the solution for such cases.

Context menu item was item was added allowing update of the web resource name. It's possible not only update filename, change extension, but also update virtual folder in which resource is stored.

Operation is a destructive one, since if someone references script by `url` from another script, such cases will not be treated.

Operation fails, if web resource is referenced somewhere in application, because it first deletes web resource, and when creates exactly the same one, but with different `url`.

### CODE REVIEW

**Comment by MscrmTools** [comment]
Hi @Shytikov, from my point of view, it is not possible to rename a web resource (like it behaves in CRM application), because it is the only unique attribute that is used to reference a web resource in other components.
I'm curious to understand how you deal with web resources already registered in other components (like form). Do you delete the "old named" web resource? Do you keep it and just create a new one?

**Comment by shytikov** [comment]
It's impossible to rename web resources, but possible to delete it and create with changed name, but with same `GUID`. I'm coping original web resource to temp variable, deleting original web resource, changing `url` in temp variable, and saving it as new web resource.

Yes, it will not work, if it already registered on forms. And code shows accurate error in this case. 

You may ask, why it's better, than manual deletion, and re-creation of file with same contents. Because of `GUID` of the resource that will not change. Thus, when it will be delivered to target environment it will replace managed resource, and change its name, not create new one, with the different name.

I'm not ready to protect this feature too much, since I know it's a bit dangerous one, and `hacky` in addition. But if used carefully, why not? 

Maybe it's possible to add it as experimental? Maybe it will help other clean up mess in web resources.

**Comment by MscrmTools** [comment]
ok!

**Comment by daryllabar** [comment]
You could search for the Id in the form XML, and replace it with the temp, and then replace it with the new version.  This is exactly what I do in the Attribute Manager

**Comment by MscrmTools** [comment]
Do not forget Ribbon... ribbon elements can be exported through SDK but not updated so we could not cover 100%

**Comment by daryllabar** [comment]
Ribbon JS Activities can't be updated?  How does the Ribbon Editor do it then?

but yes, the logic to handle that would be extremely difficult, and very brittle I'm sure.

**Comment by MscrmTools** [comment]
throuhg solution import/export, but trust me, SDK cannot

**Pull request merged**
