### PR TITLE
Splash screen optimizations

### PR DESCRIPTION
**Pull request by shytikov**
I've created three asynchronous tasks:

* Showing splash screen;
* Loading available plugins;
* Checking new version;

They are starting working simultaneously on program load. When they are all done, main window show up.

### CODE REVIEW

**Comment by MscrmTools** [comment]
I trust you so I merge the pull request :)

**Comment by daryllabar** [comment]
Have you been able to determine the performance gain?

**Comment by shytikov** [comment]
I've not measured, I don't think it is that significant. 

New version check and plugins loading operations was executing one after another. And splash-screen was in separate thread just waiting for three seconds.

Taking into account that new version check happens only once a while, this is only plugins loading time in one thread and three seconds delay in another thread. And I haven't optimized plugin loading time (yet).

But the real benefit of this code is a fact that plugins now are loaded when main window is hidden. Thus, user don't see how code adds plugins' controls to main page.

And, definitely, splash screen returns focus to main application, as it supposed to do.

**Comment by shytikov** [comment]
@daryllabar regarding performance gain from parallel execution.

I've added simple Parallel.ForEach in [my plugin](https://github.com/Cinteros/Cinteros.XrmToolBox.SolutionVerifier/commit/ff38b959c780db5446d8939f8bd486e694bef4f5) in the code when I'm pulling solutions information from several servers. When I was developing that fix, I was measuring performance.

I don't have these results already. But when polling six or seven servers in parallel I achieved three times performance gain at the end. I believe it's too optimistic to say it would be possible to get such a gain everywhere, but 20-30% it's quite feasible, I guess.

My PC have 2 physical CPUs and 4 logical.

**Comment by shytikov** [comment]
@daryllabar I made some performance measurements (very basic ones) for #12.

**Pull request merged**
