### PR TITLE
Small usability improvements for plugin search

### PR DESCRIPTION
**Pull request by shytikov**
* Disabling search box if Home screen is invisible (and enabling it when it become visible again);
* Focus on plugins filter box on Ctrl+F;

### CODE REVIEW

**Comment by MscrmTools** [comment]
For Ctrl+F stuff, you don't check if HomePage is actually selected. As I already implemented Ctrl+F in WebResourcesManager (for example), I'm not sure about the behavior...

**Comment by shytikov** [comment]
You right, let me check...

**Comment by shytikov** [comment]
This should be better. Sorry.

**Comment by MscrmTools** [comment]
Thank you

**Comment by MscrmTools** [comment]
Just found another problem. 

If plugin list has been scrolled down, redraw of found plugins does not happen correctly. Remaining plugins are not on the top of the plugins container

**Comment by shytikov** [comment]
Interesting... let me try to fix this one as well.

**Comment by shytikov** [comment]
I will probably revert my anti flickering code, since it seems to be interfering with `OnPaint` of `SmallPluginModel` and to do everything 100% I should investigate deeper, and this will may cause April release to come out with such a nasty bug...

Without antiflickering it searches indeed faster and maybe optimization done this way don't worth it.

**Pull request merged**
