### PR TITLE
Added URL entry to autopopulate some connection details

### PR DESCRIPTION
**Pull request by arangas**
In regards to #148, please review and see what you think of this. (There are certain parts of this dialog, especially the IFD checkbox that I'm not sure how should behave.) Looking forward to your feedback.

### CODE REVIEW

**Comment by MscrmTools** [comment]
As ServerName textbox shouldn't contain protocol part (http:// or https://), Are your sure that instanciating an Uri with this value works?

**Comment by arangas** [comment]
My understanding is that there is a concern that the Server Name textbox would be populated with the URL scheme. This is not how the code has been written and is not what occurs. It may be a good idea to try this out and perhaps step through the Leave event to see the behaviour.

Also I forgot to mention that I fixed tab ordering on this dialog as part of this PR as well.

**Comment by rappen** [comment]
:+1: to this, as _my_ understanding is that you should be able to simply take a url to a CRM from the browser address field and XTB will break it up into relevant parts and help you configure your connection. Great improvement, as there have been hundreds (thousands?) of issues and "bug reports" from users who can't set up their connection correctly.

**Comment by MscrmTools** [comment]
ok, I see... I didn't read properly your code change.
My only concern is your code make using protocol mandatory in servername textbox which has never been the behavior so far. So it will produce another hundreds of issues about how to connect to properly to a CRM organization.
We should add this check only if the servername textbox starts with 
"http"

**Comment by MscrmTools** [comment]
I would prefer to avoid merging this pull request for now as I need to study new Microsoft.Xrm.Tooling assemblies to support Multi Factor Authentication.
Until this study is not achieved, I will hang on this PR

**Comment by arangas** [comment]
Could you please demonstrate how protocol becomes mandatory in the server name textbox? There are no changes to the behaviour of any of the existing controls. The additional URL textbox populates them, but that is all.

Actually, to make this more obvious I would add a dividing line between the new textbox and existing controls, if this PR looks like it will progress.

I can't see how authentication is related to this PR. Obviously it's up to you to determine where this goes from here.

**Pull request closed without merging**
