### PR TITLE
Update ExcelDocument.cs

### PR DESCRIPTION
**Pull request by cint-mats**
Removed if statement requiring the entity to have localized label for generating sheet in Excel document. #359

### CODE REVIEW

**Comment by MscrmTools** [comment]
I think your change won't work when exporting more than one entity without displayname, since two Excel sheets cannot have the same name.
Can you confirm? You can maybe put the logical name when no displayname is available

**Comment by cint-mats** [comment]
As far as I can test, it works. I created two N:N relationships and generated the metadata for those entities using the plugin with my change.

The sheet name is primarily the schema name of the entity, with the displayname prepended if there's room. When there's no displayname in CRM, "N/A" will be used as displayname. The code creating the sheet will replace "/" to " " (among other characters I suspect upsets Excel). 

Examples of sheetnames:
 "N A (mats_entityX)" for mats_entityX
"mats_an_entity_with_a_very_long_" for mats_an_entity_with_a_very_long_name

**Comment by MscrmTools** [comment]
ah ok... didn't remember this one... Ok, so let's merge the PR

**Comment by cint-mats** [comment]
It's a bit hard to remember all details. :)

**Pull request merged**
