### PR TITLE
Merge remote-tracking branch 'refs/remotes/MscrmTools/master' into Fast-dependencies-remover

### PR DESCRIPTION
**Pull request by isultan69**
I developed this new plugin, it helps to remove all field dependencies from attribute (sometimes we want to delete an attribute but it is on forms, views, etc). The plugin is a Beta version and have a little bugs. It was a console application but I tried to make a GUI similar to your other plugins.
I'll improve it more but I this is ready to use

### CODE REVIEW

**Comment by daryllabar** [comment]
This is already something my Attribute manager does.  Ever thought of combing forces?

**Comment by daryllabar** [comment]
Actually, it nearly does.  It replaces it.

**Comment by isultan69** [comment]
You mean Attribute Bulk Updater?

**Comment by MscrmTools** [comment]
I don't understand why a pull request? There is no file changed or added?

**Comment by daryllabar** [comment]
@isultan69 no, https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools.

**Comment by isultan69** [comment]
@MscrmTools I don't know what happenned. Yesterday I saw all the files
@daryllabar I'll check your Attribute Manager maybe I could combine forces with yours. Why is it separated from XTB?

**Comment by MscrmTools** [comment]
@isultan69 I never release tools from other developers with XTB. The "other tools" you see were developed by one of my colleague that stop the development (that's why I included them) or one from the company I'm working for (Javista)
So, anyway, I won't include your tool in the global XTB package

**Comment by isultan69** [comment]
Ok I Understand. So you can close this pull request. I'll see if I have something to add to Daryl's Plugin.

**Pull request closed without merging**
