### PR TITLE
Bricksfixes

### PR DESCRIPTION
**Pull request by CRMBricks**
Hi

On a system with many languages installed, we had trouble with the translation plugin. I analyzed the problems and did some changes to the code.

- I dont know how they get there in the first place. But without removing duplicate languagecodes in localized labels (entity and attribute class) the crm-service always threw a "An item with the same key has already added" when trying to execute request.
- Sitemap module: Wrong cell got checked for "title" or "description"
- In sitemap xml title has always has to be first (before description), otherwise crm throws an error.

Hope you can integrate those changes

Regards
daniel

### CODE REVIEW

**Comment by MscrmTools** [comment]
Thank you very much for this pull request. 
I'm in the middle of rewriting this plugin so I won't merge the pull request but take each change individually when working on it.

**Comment by CRMBricks** [comment]
this is also good :)
espacially the part with remove duplicates is important, otherwise the system cant publish customizing anymore.

regards

**Comment by shytikov** [comment]
@CRMBricks, are you aware, that you just exposed your gembox license code?

**Comment by CRMBricks** [comment]
@shytikov yes i was aware of that. just took me some time to figure out how to remove it completely. thanks a lot  anyway!

**Comment by MscrmTools** [comment]
Just a comment. I reviewed your changes and I don't understand the following comment : "the part with remove duplicates is important".
The line above the code you changed is creating a new Label object, which should erase the previous Label object. So there is no existing langauge code already in that object.
Am I wrong?

**Comment by CRMBricks** [comment]
This is the error we got everytime without the removeAll fix:

scr

The fix makes sure to remove any LocalizedLabel from the list with the same languagecode. Because if there are two LocalizedLabels in this list with same languageCode you get the error from above and crm cannot pulbish customizings anymore. you have to delete these labels in the database to fix the org.

This approach just keeps the last one. Of course you could also check if there already is an item with this language code is in this list and then aboard the add command.

**Pull request closed without merging**
