### PR TITLE
Speed up tool startup performance.

### PR DESCRIPTION
**Pull request by yagasoft**
Added: plugin cache to speed up startup time.
Improved: store update check speed on startup.

### CODE REVIEW

**Comment by yagasoft** [comment]
@MscrmTools 
Managed to find the branch in a cloud backup.
I fixed the issue you were facing. Please retest and let me know if further work needs to be done.

**Comment by MscrmTools** [comment]
@yagasoft Thank you! I guess I found how to fix it too.

But I'm facing another issue. The issue occurs when adding a new tool from Tool Library, there should be a rescan but PluginsX property is null so it crashes. I don't really understand why PluginsX is null whereas it should have been recomposed

**Comment by yagasoft** [comment]
@MscrmTools 
Indeed, I tried multiple scenarios from scratch and found a few issues. They are fixed now; please pull the new commits.

I wanted to make sure that the concept was acceptable before proceeding with full testing. I will now switch my main binary to this one and use it for everyday activities.

**Comment by MscrmTools** [comment]
Can you double check the scenario with Tool Library? I do not see so much difference between both of your PRs...

**Comment by yagasoft** [comment]
In this PR, I fixed a few things (below is one of them).
image

**Comment by MscrmTools** [comment]
ok, I will merge the PR and see how it goes

**Comment by yagasoft** [comment]
@MscrmTools 
I sent you a message on Gitter.

**Comment by BetimBeja** [comment]
@yagasoft @MscrmTools 
doesn't the following change undo the "trick" to open XrmToolBox with no access to NuGet (ex. in a firewalled environment)?
image

I think this was a regression.

**Comment by MscrmTools** [comment]
I will double check with no internet connection available

**Comment by yagasoft** [comment]
Let me try to handle that specific scenario and keep the rest of the exceptions unhandled.

**Comment by MscrmTools** [comment]
It still works without any Internet connection

**Comment by MscrmTools** [comment]
@yagasoft, one weird thing, not related to the tool itself, it seems not possible to debug step by step anymore.
Screenshot below is in French, but it says basically "Deletion of auto property xxx stops debug session to continue"

image

Any idea why it says that?

**Comment by yagasoft** [comment]
The screenshot contains missing properties. The 'master' branch contains the correct ones ...
image

**Comment by MscrmTools** [comment]
Ok, I think we are good now! Thank you very much @yagasoft 

I plan to release this new version of XrmToolBox tomorrow or early next week

**Comment by rappen** [comment]
Opening a few of tools, using XTB commit d967eb98ce5b1916d5e6c3179b689c1f9e932cd4
Tools are all the latest, installed from **Tool Library**.

A few... sorry... hope it helps!!

Tool FetchXML Builder:
image

Tool Plugin Trace Viewer:
image

Tools Custom Action/API Tester:
image

Tool Latebound Constants Generator and UML Diagram Generator:
image

Tool Related Records Analyzer, clocking _Analyze xx_:
image

**Comment by yagasoft** [comment]
I traced the issue to the commit below. I will try to trace it and see where it leads me.
image

**Comment by yagasoft** [comment]
This is the cause of the issue:
image

**Comment by MscrmTools** [comment]
@rappen do your tools used version 3.0.6 or 3.1 of DockPanelSuite?

**Comment by BetimBeja** [comment]
> @rappen do your tools used version 3.0.6 or 3.1 of DockPanelSuite?

From the screenshot you (@yagasoft or @MscrmTools ) referenced the wrong assembly version of `WeifenLuo.WinFormsUI.Docking Version=1.` even though the hint path points to the right package.

**Comment by yagasoft** [comment]
@BetimBeja 
It seems that the authors of the package made a mistake (or intentional for some reason), and set the assembly version to 1.0.0.

**Comment by yagasoft** [comment]
image

**Comment by yagasoft** [comment]
@rappen 
I downloaded your project, upgraded the package version to 3.1.0, and found the error below. Upon removing that line, the project was built and ran successfully.

Regarding the other errors, we changed the way we store the list of plugins to make it a lot faster. Please check the code and let us know if there are improvements to be made for better backward compatibility.

image

**Comment by rappen** [comment]
> @rappen do your tools used version 3.0.6 or 3.1 of DockPanelSuite?

3.0.6, since I have to for XTB. I tried 3.1.0 but had to go back to 3.0.6.

**Comment by rappen** [comment]
> > @rappen do your tools used version 3.0.6 or 3.1 of DockPanelSuite?
> 
> From the screenshot you (@yagasoft or @MscrmTools ) referenced the wrong assembly version of `WeifenLuo.WinFormsUI.Docking Version=1.` even though the hint path points to the right package.

Sorry, I can't get the `Version=1` in my code. Help?

**Comment by BetimBeja** [comment]
> > > @rappen do your tools used version 3.0.6 or 3.1 of DockPanelSuite?
> > 
> > 
> > From the screenshot you (@yagasoft or @MscrmTools ) referenced the wrong assembly version of `WeifenLuo.WinFormsUI.Docking Version=1.` even though the hint path points to the right package.
> 
> Sorry, I can't get the `Version=1` in my code. Help?

Not a problem with your code. Version `3.1.0` of `DockPanelSuite` doesn't specify `AssemblyVersion` so it is being generated as `1.0.0.0`. We should raise an issue with `DockPanelSuite` so that they can fix this problem 😄

**Comment by yagasoft** [comment]
> > > @rappen do your tools used version 3.0.6 or 3.1 of DockPanelSuite?
> > 
> > 
> > From the screenshot you (@yagasoft or @MscrmTools ) referenced the wrong assembly version of `WeifenLuo.WinFormsUI.Docking Version=1.` even though the hint path points to the right package.
> 
> Sorry, I can't get the `Version=1` in my code. Help?

Sure, I can help you ... as mentioned in my previous comment, the solution is to simply remove the redundant reference to 'VS2005 theme' in your code. I tried it with v3.0.6 referenced in your project and v3.1 referenced in XrmToolBox, and it worked perfectly.

**Comment by yagasoft** [comment]
> > > > @rappen do your tools used version 3.0.6 or 3.1 of DockPanelSuite?
> > > 
> > > 
> > > From the screenshot you (@yagasoft or @MscrmTools ) referenced the wrong assembly version of `WeifenLuo.WinFormsUI.Docking Version=1.` even though the hint path points to the right package.
> > 
> > 
> > Sorry, I can't get the `Version=1` in my code. Help?
> 
> Not a problem with your code. Version `3.1.0` of `DockPanelSuite` doesn't specify `AssemblyVersion` so it is being generated as `1.0.0.0`. We should raise an issue with `DockPanelSuite` so that they can fix this problem 😄

Unfortunately, it is indeed a problem with @rappen code. I downloaded the DockPanel solution, fixed the 'AssemblyVersion', and rebuilt XrmToolBox; however, it still gave the same exact error.

The reason is because the reference I pointed out earlier is actually removed from the latest version of their code. In addition, as far as I can tell, the reference to it in @rappen code is not required. Please correct me if I am wrong.

**Comment by rappen** [comment]
> @rappen I downloaded your project and found the error below. Upon removing that line, the project was built and ran successfully.
> 
> Regarding the other errors...

Ok so the 3.1.0 version does not support the same Theme. I can remove that, but it requires an update release before new version of XTB, right?

**Comment by yagasoft** [comment]
Yes, I believe so.

I am not sure how to fix the other errors though at the moment, as I believe it requires a redesign to avail the plugin list through the proper interface.

A temporary solution would be to access the new Plugins property with the new type, but I find this a little cringy, as it's so hacky :D; I would rather expose it through the plugin interface for proper access.

**Comment by yagasoft** [comment]
@rappen 
If you want, I can add a reference of the new Plugins property to the PluginControlBase class. @MscrmTools, please let me know what you think.

**Comment by rappen** [comment]
I don't know right now. I would dig into the code (in all different I sent earlier) and maybe all of my tools, to make sure.
And probably all developers, if you change the core of the tool? If we are using at the interface and public methods, and this is changed...? Then I guess the will be a new version 2.2021.x... Also still have 1.2021.x for tools not yet updated (it needed).

I know I may have missunderstand it (I read like crap, I know) - if so don't listen to me! 😉

**Comment by yagasoft** [comment]
@rappen 
Breaking changes are software's worst enemy. People hate them with a passion for a reason indeed. That being said, I believe that as long as library upgrades are done carefully and the interface behaviours don't change, it's safe to go forward.

Any behavioural change outside of the standardised interfaces is fair game, in my humble opinion.

Announcing potentially breaking changes ahead of time is a perfectly valid approach. For this release, I believe we could analyse those changes, revert them for now, announce their eventual arrival with a definite date, and wait for feedback.

As far as I can tell, the only breaking change (outside of the contractual interfaces) is the upgrade of the Dock package. @MscrmTools feedback is invaluable to consolidate all other potential issues.

**Comment by rappen** [comment]
I realize and agree we all want it to be update and newer and smarter code 😊
Problem is many tools that were created long ago and not really updated by anyone... (not talking about me, but I know my update will take longer now)

I think [all other tools](https://github.com/MscrmTools/XrmToolBox/pull/1088#issuecomment-990139232) than PTV tool have other problems than `DockPanelSuite`.
I have not looked inte these problems, but my first look something about `PluginControlBase` anyway...

**Comment by yagasoft** [comment]
@rappen 
I think we can summarise our discussion into the following items:
1. If a library upgrade is not 'required' by a specific function, or at least contains an important bug fix, then I believe it should be postponed to a later version
a. XRM package upgrades are required to maintain proper connectivity requirements
b. DockPanelSuite upgrade requires _reassessment_
2. The change to the 'Plugins' property is justified because it's not on the standardised interface
a. It can be safely _added_ to the interface of PluginControlBase without breaking backwards compatibility
b. An announcement of this change must be made for authors to fix their code
3. There are no interface changes in this version that I can see
Would you say that this is an accurate and fair summary?

**Comment by yagasoft** [comment]
Please note that I mean C# Interface (code contract) -- not UI.

**Comment by rappen** [comment]
> 1. If a library upgrade is not 'required' by a specific function, or at least contains an important bug fix, then I believe it should be postponed to a later version

We do want to be as "new" as possible, only stop update if it really needs of some reason.

>    a. XRM package upgrades are required to maintain proper connectivity requirements

You mean `Microsoft.CrmSdk.x` or XTB (`XrmToolBoxPackage`)? Just to be clear 🙂

>    b. DockPanelSuite upgrade requires _reassessment_

If it is only only me and only PTV - get the new version!

> 2. The change to the 'Plugins' property is justified because it's not on the standardised interface

Just to be clear, again ;)
When you say 'Plugins', do you mean 'Tools'?

Ok, we know more than only the `interface` and we are working with as we can, and I am using some "public properties" and "public methods" - to get it to work a bit cooler.
In many cases I tell @MscrmTools of my ways of coding a tool, but mostly I ask and to get advice. And even to add new things to XTB to make more possibly.
Right, it may be the correct thing to only look at `interface`, but we all now more to it. So changing/remove things not in interface may be dangerous for the real world we are in 😉

>    a. It can be safely _added_ to the interface of PluginControlBase without breaking backwards compatibility
>    b. An announcement of this change must be made for authors to fix their code

It is a hard case when there are awesome tools that are not really updating anymore by the author. It is open source and free to pick up and update/or a new release etc... but we never see that happen 😉

> 3. There are no interface changes in this version that I can see

Ok, nice 🙂
But you see above...

Anyone know the crashes in my some of my tests above? I mean the are working fine so far, but what is wrong now?

> Would you say that this is an accurate and fair summary?

Most it: we can not go 100% "we have interface not changed, so screw you 😎". This is a lot more community, and the `interface` is never 'gone', ond we communicate.
I mean - we all love each other ❤

Finally - any thoughts from @daryllabar too?

_PS - I hope you see my friendly tone - I Iove that you try to improve it even more! Just not to be too white/black on how all developers out there._

**Comment by MscrmTools** [comment]
Ok, I must admit I'm not sure to understand everything (still my bad English and/or lack of knowledge for some dev aspects).

So, I did understand that DockPanel latest version can be problematic. I think we can revert to version 3.0.6 without issue since no new feature was included in version 3.1w

Is there another issue that needs to be fixed on XTB side or is it on @rappen tools side?

**Comment by rappen** [comment]
I just added yesterday my random tests, with only PTV had DockPanel error, the other where very ok in 1.2021.9.x version but failed with last XTB code. I have not dig into the errors, only added the screenshots here.
The non-DockPanel-errors should probably get checked from someone who knows XTB and know the changes. For me it would probably take a long... 😕

(I know my English is bad with aphasia now too)

**Comment by yagasoft** [comment]
I am sorry to hear about your illness @rappen.

I fully understand your point of view. I am strict by nature, which gets me carried away sometimes. We are all friends trying to make life better for each other indeed; I apologise if I appeared forceful or aggressive.

To clarify, the changes I made affected a property in `PluginManagerExtended` class called `Plugins`. The property is populated by a compositor automatically. The issue is that it takes a long time to scan the plugins, which causes major delays at the app's start-up.

This issue has caused so much pain for many of my colleagues who have slow PCs. It can take up to two minutes, no joke, for the tool to start; hence, I proceeded to find a solution.

The change caused a backward compatibility issue in that I changed the name of that property to prevent anyone from using in any future coding activity. The reason is that it's not ideal and might cause unnecessary delays if all that's wanted is some metadata information.

The new property is much lighter and contains all the info that could possibly be required. The speedup is in the order of 7-10 times.

That's the only thing that might affect existing plugins. If you feel that it's too risky, please discuss a rollback with @MscrmTools.

This is the line causing the error in your tool:
image

Another **solution**: I could try to maintain the old property as-is, just rename the new one instead and use it everywhere in the core assembly. Please let me know and I will proceed to implement this change by tomorrow evening.

**Comment by MscrmTools** [comment]
@rappen, not sure what this `FixFormForTool` is doing but I can run CAT with the latest PR. Can you check if it's ok for you too?

**Comment by rappen** [comment]
Thanks @yagasoft 
New version is a lot better 🙂
Still problems with three last tools for my tests (LCG, UDG, RRA).
You see easily how to fix it? Shall I dig down to the code (will not be today, sorry)? Or you just go on and I fix it when I have time and understand the problem? 🙂

@MscrmTools the `FixFormForTool` is to correct the layout, as the code is the same for two tools. So the tools have this to fix their flavor.
I guess this is problem?
image

Of this?
`PluginManagerExtended.Instance.Plugins.Any(p => p.Metadata.Name == catTool.ManagerTool)`

I would gladly change to something else that works...

**Comment by MscrmTools** [comment]
The last one is the issue I guess as Plugins connection is what has been updated

**Comment by MscrmTools** [comment]
@rappen can you fix your tools regarding Plugins collection? This way, I will be able to release a new version of XrmToolBox without impact for your tools

**Comment by yagasoft** [comment]
@rappen 
What is the exact error, please? so that I can check whether I can assist in the fix.

**Comment by rappen** [comment]
@MscrmTools I will try now! Any idea to help how to change this?
`PluginManagerExtended.Instance.Plugins.Any(p => p.Metadata.Name == catTool.ManagerTool)`

@yagasoft this 👆

Find another error in LCG/UDG - it is actually only me and myself only code, will fix that too 🙄

**Comment by MscrmTools** [comment]
@rappen, what this line is made for? You want to find if a specific tool is installed right?

**Comment by rappen** [comment]
This is doing, show integrated if tool is installed: https://www.screencast.com/t/EFbYKJffK0k
(sorry ugly color)

I could just remove it and show message if the tool is not found. If the same thing is not easy in an other way.

**Comment by rappen** [comment]
Fixed, releasing soon.
https://github.com/rappen/CustomActionTester/commit/db622770c15c20bf4aa2264d58feb31b40229f89

Is that all for you? 🙂

**Comment by yagasoft** [comment]
@rappen 
I tested your tools, and they work fine after the latest update I pushed (except LCG, which has an error not related to this update, I think). Even CAT works fine with the Custom API Manager with that line included.

I am not sure why you removed it. If it's causing an error, please share it with me to fix it. I want to make sure that no other tools will have an issue, as you said before.

**Comment by yagasoft** [comment]
Fixed an issue with ValidatedPlugins access in PR1092.

**Comment by yagasoft** [comment]
I am getting the following error in anything related to LCG:
image

**Comment by yagasoft** [comment]
I am getting the same error in older XrmToolBox versions as well; so I think it's not related to the update.

**Comment by rappen** [comment]
@yagasoft like you said - CAT/CAPIT is fixed, and LCG is probably fixed, please report the issue on https://github.com/rappen/LCG-UDG instead as this is not from XTB update.

**Comment by yagasoft** [comment]
@rappen 
Issue reported on repo.

@MscrmTools 
I opened one final PR to make sure that we keep the old properties as-is.

I have been using this version for everyday work, and it seems to be stable so far. I believe that it is ready from @rappen and my side. Please let me know if any more work is needed, and I will surely lend a hand.

**Comment by MscrmTools** [comment]
Thank you very much.
I'm off tomorrow but I will merge the PR on Thursday and release a new version of XrmToolBox

**Pull request merged**
