### PR TITLE
#565 Consolidating packages

### PR DESCRIPTION
**Pull request by shytikov**
Fixing visual studio design-time issues. 

Would be so nice to have this projects uploaded to NuGet, as well!

### CODE REVIEW

**Comment by shytikov** [comment]
I believe these changes not needed anymore, since dependency assemblies are managed in the real time?

**Comment by MscrmTools** [comment]
Not sure... I fixed the reference binding when running XTB, not when designing plugins in VS...

**Comment by shytikov** [comment]
So reopening then :)

**Comment by MscrmTools** [comment]
Did it myself... closing this PR

**Pull request closed without merging**
