### PR TITLE
Add Travis CI build script to be able to continually make sure pull requests build correctly.

### PR DESCRIPTION
**Pull request by Davesmall28**
HI Tanguy.

If you sign into Travis CI (https://travis-ci.org) with your github login it will create a Webhook into your repository and included in this pull request is the Travis CI build script that tells it the solution name to build and the language to build against.

As with any other open source we can then start writing unit tests for XrmToolBox and make sure core components to do regress in newer versions.

Instructions for Travis CI
1. Go to https://travis-ci.org
2. Sign in with github username
3. Go to https://travis-ci.org/profile/MscrmtOOLS
4. Click sync now
5. This should discover MscrmTools/XrmToolBox and your other public repositories
6. Click the slider to turn the build to on.

How to test Travis CI
A. Make a commit to MscrmTools/XrmToolBox.
B. Go to your repository's settings page, click on "Webhooks & Services" on the left menu, choose "Travis CI" in the "Services", and use the "Test service" button located near the top.

Regards

David

### CODE REVIEW

**Comment by MscrmTools** [comment]
Hi Dave,
I didn't know Travis but it seems really interesting! 
Let me just read more about Travis before pulling your request but I will do it

**Comment by Davesmall28** [comment]
No problem! As long as you are happy to open source your code on GitHub they are happy to do the continuous integration and I would like to start writing unit tests so we can keep XrmToolBox getting better with each version.

**Comment by shytikov** [comment]
Afterwards can we discuss which Unit testing framework we should stick to?

I don't have that much experience in unit testing to claim myself en expert in this area, but I would vote for `xUnit` if it's supported on `Travis`.

**Comment by MscrmTools** [comment]
I'm really not an expert on Unit Testing...
The only thing I know is that not every testing framework is able to read/manage all kinds of variables/properties, especially when they are private, sealed and so on... 
For example, using RhinoMocks, I wasn't able to test methods that use EntityMetadata which has some deeply locked properties you can't mock. I had to use Fakes from Microsoft to do so.

So we need to select carefully what framework to use

**Comment by MscrmTools** [comment]
Ok... I just read some documentation about Travis and xUnit but can't find anything about mocking objects so I don't know if metadata are testable through this framework
If someone can confirm it is possible

**Comment by Davesmall28** [comment]
Hi,
I have used Moq with NUnit on Travis but happy to go with xunit and do not envisage any problems using Moq.

If we need to use fakes for parts I would be happy with that but Moq for most of the implementation.

**Comment by MscrmTools** [comment]
And I read that Fakes is not implemented in Travis

**Comment by Davesmall28** [comment]
We may never get close to 100% code coverage without fakes but I think to have continuous integration and high code coverage is still a benefit for doing this.

**Comment by Davesmall28** [comment]
I am still learning GitHub as this one commit for pull request has now got three more commits but still only shows the one file I intended to merge into master.  Any help would be appreciated.

**Comment by shytikov** [comment]
@Davesmall28 I would be glad to help. 

The issue, if I got what you're talking about is the branching strategy. You've created pull request right from your branch `master`. This basically means that you indicated your branch `master` as a source for code that should fix certain issue in `upstream`, which is `master` branch of Tanguy's repository.

Github will collecting all code you will add to your `master` and add it to this pull-request. These commits will be treated as corrections to fix you provided earlier. This will be happening until Tanguy will decide to merge your pull-request, indicating that issue is closed.

Probably you don't want your code from your `master` automatically appear in this (or any other) pull-request. In this case you probably should develop fixes in separate branches. This will isolate your fix and your `master` from Mr. T's `master`.

It's a bit tricky from the first sight, but it makes sense when you deal with lot's of features in progress in the same time.

**Comment by Davesmall28** [comment]
Cheers @shytikov 

Yeah so I should branch from TravisCI branch to Tanguy's master instead I merged from TravisCI to my master and then across to Tanguy's master.

Any new commits I do will be done on a branch and that will isolate my master from any changes until we figure out what we want to do with this pull request.

**Comment by shytikov** [comment]
@MscrmTools Can you point me to the article about Fakes on Travis?

It actually should not matter... Travis needs support of UnitTest runners, because `xUnit`, `NUnit` or `MSUnit` tests should be run differently, but than `fake` library used by unit test like a regular dependency `dll`. So does not matter do they 'support' it or not...

**Comment by shytikov** [comment]
@Davesmall28 I'm not sure, that I'm following you, since I haven't tried Travis yet, but I assume, that Travis actually makes some changes on behalf of you in your `fork` of Tanguy's repository.

In this case the process should look like following:

* You creating separate branch in your `forked` repository for `travis` functionality;
* You switching to new branch in your `fork` and doing all needed changes (or Travis does them on your behalf);
* From this branch you're creating pull-request to Tanguy's master;
* You switching back to your `master` or any other branch and continue working on other tasks and all your further commits are completely separated from what you have already done for Travis;
* Tanguy reviews changed you did and accepts or refuses them;

**Comment by shytikov** [comment]
It might happen, that `Travis-CI` will not work for us at all.

It's *nix based platform. It builds `C#` with `Mono`. 

> Currently, Travis builds your C#, F#, and Visual Basic project with the latest version of the Mono runtime on Linux. It is based on the ECMA C# and CLR standards but might not be a perfect replacement for the Microsoft .NET Framework.

From [here](http://docs.travis-ci.com/user/languages/csharp/).

Another alternative could be [appveyor](https://ci.appveyor.com)

**Comment by MscrmTools** [comment]
It seems a nice solution!

**Comment by Davesmall28** [comment]
We can choose to have a CI build of Travis CI on mono and appveyor.

Is there reason to not be aware if the XrmToolBox will build and run on mono?

**Comment by skfd** [comment]
XrmToolBox will not do mono, we depend on closed source windows libraries.

Appveyor is a good choice. But if you want I can setup TeamCity.

**Comment by MscrmTools** [comment]
I'm starting to implement appveyor. It will requires some time to update two plugins and implement ILMerge where it is required.

**Pull request closed without merging**
