### PR TITLE
Accesschecker

### PR DESCRIPTION
**Pull request by isultan69**

### CODE REVIEW

**Comment by MscrmTools** [comment]
Can you comment what your changes are?

**Comment by isultan69** [comment]
Changed user view from firstname/lastname to fullname/domainname because lastname's requirement level can be changed to optional and that makes a bug for users with no lastname (still asking to choose a user) but fullname is system required. It's a better option.

Also name of the selected object is not filled, a o I fixed it

**Comment by MscrmTools** [comment]
Ok, I see there are some files from other project in your pull request. Is that expected?

**Comment by isultan69** [comment]
I don't recognize that change in metadata generator. Maybe because I made some changes to let it compile (the gembox.license). I made undo changes before the pull request, maybe I forget this one

**Comment by isultan69** [comment]
Removed all not recognized changes made to Metadatagenerator. Now I sent just what I wanted to update

**Pull request merged**
