### PR TITLE
Crm2016

### PR DESCRIPTION
**Pull request by Nazi-Nigger**

### CODE REVIEW

**Comment by MscrmTools** [comment]
What is the purpose of this pull request, please?

**Comment by daryllabar** [comment]
Looks like none of these commits were made by @Nazi-Nigger (My vote for worse name ever).   Maybe it was an attempt to get his/her local?

**Comment by Nazi-Nigger** [comment]
Perhaps the best ironic or sarcastic  name ever 😃


Sent from my Windows Phone
________________________________

**Comment by skfd** [comment]
There's no new code. Can be safely burnanate.

**Comment by shytikov** [comment]
"burnanate"? Cannot find definition...

I'm so lost... My vote for most 'art-house'-like discussion ever! :+1:

**Comment by daryllabar** [comment]
Burnanate is a made up word.  I've only ever seen it in the homestar runner Trogdor video: https://youtu.be/7gz1DIIxmEE

**Pull request closed without merging**
